export const pocketBaseCollections = {
  users: "app_users",
  notifications: "notifications",
  recipients: "notification_recipients",
  preferences: "notification_preferences",
  deliveries: "notification_deliveries",
  pushTokens: "push_tokens",
  webPushSubscriptions: "web_push_subscriptions",
  providerEvents: "notification_provider_events",
  webhookLogs: "webhook_logs",
  vehicles: "vehicles",
  chauffeurs: "chauffeurs",
  bookings: "bookings",
  payments: "payments",
  discounts: "discount_codes",
  blockedSlots: "blocked_slots",
  settings: "app_settings",
  smsConsents: "sms_consents",
  passwordResetTokens: "password_reset_tokens",
  calendarFeedTokens: "calendar_feed_tokens",
  mockSmsMessages: "mock_sms_messages",
  pushReceipts: "push_receipts",
  flightSnapshots: "flight_snapshots",
  flightTracking: "flight_tracking",
  flightProviderEvents: "flight_provider_events",
} as const;
