import { randomUUID } from "crypto";
import { assertFutureBookingTime } from "@/lib/booking-time";
import { getNotificationTimeZone } from "@/lib/admin-settings";
import { zonedDateTimeToDate } from "@/lib/notifications/time";
import { getPocketBaseClient } from "./client";
import { pocketBaseCollections } from "./collections";
import { createWithLegacyId, first, legacyId } from "./core";

export interface VehicleRecord { id: number; make: string; model: string; year: number | null; colour: string | null; plate: string | null; status: string; createdAt?: string; }
export interface ChauffeurRecord { id: string; name: string; email: string; phone: string; status: string; avatarUrl?: string | null; vehicleId?: number | null; vehicle?: VehicleRecord | null; }
export interface BookingRecord { id: number; reference: string; tripType: string; date: string; time: string; duration: number; name: string; email: string; phone: string; notes: string; status: string; tripDetails: string; chauffeurId?: string | null; smsConsentVersion?: string | null; smsConsentedAt?: string | null; pin?: string | null; pinConfirmedAt?: string | null; createdAt: string; }
export interface PaymentRecord { id: number; bookingReference: string; amountCents: number; currency: string; method: string; status: string; transactionReference: string | null; notes: string | null; paidAt: string | null; createdAt: string; updatedAt: string; customerName?: string; customerEmail?: string; tripType?: string; tripDate?: string; tripTime?: string; bookingStatus?: string; tripDetails?: string; }
export interface DiscountCodeRecord { id: number; code: string; label: string; kind: "percent" | "fixed"; value: number; active: number; maxRedemptions: number | null; redemptions: number; expiresAt: string | null; createdAt: string; updatedAt: string; }
export interface BlockedSlotRecord { id: number; title: string; date: string; endDate?: string; isFullDay: number; time: string; duration: number; recurring: string; chauffeurId?: string | null; createdAt: string; }
export class DiscountCodeError extends Error { constructor( message: string ) { super( message ); this.name = "DiscountCodeError"; } }
export const DEFAULT_BOOKING_BUFFER_MINUTES = 30;
export function normalizeDiscountCode( code: string ) { return code.trim().toUpperCase().replace( /\s+/g, "" ); }

const pb = () => getPocketBaseClient();
const date = ( value: unknown ) => value ? String( value ) : "";
const nullable = ( value: unknown ) => value ? String( value ) : null;
const number = ( value: unknown ) => Number( value || 0 );
function vehicle( record: Record<string, unknown> ): VehicleRecord { return { id: number( record.legacyId ), make: String( record.make ), model: String( record.model ), year: record.year === "" || record.year == null ? null : number( record.year ), colour: nullable( record.colour ), plate: nullable( record.plate ), status: String( record.status ), createdAt: date( record.created ) }; }
function chauffeur( record: Record<string, unknown> ): ChauffeurRecord { const expanded = record.expand && typeof record.expand === "object" ? ( record.expand as Record<string, unknown> ).vehicle as Record<string, unknown> | undefined : undefined; return { id: String( record.legacyId ), name: String( record.name ), email: String( record.email ), phone: String( record.phone || "" ), status: String( record.status ), avatarUrl: nullable( record.avatarUrl ), vehicleId: expanded ? number( expanded.legacyId ) : null, vehicle: expanded ? vehicle( expanded ) : null }; }
function booking( record: Record<string, unknown> ): BookingRecord { const chauffeurRecord = record.expand && typeof record.expand === "object" ? ( record.expand as Record<string, unknown> ).chauffeur as Record<string, unknown> | undefined : undefined; return { id: number( record.legacyId ), reference: String( record.reference ), tripType: String( record.tripType ), date: String( record.pickupDate ), time: String( record.pickupTime ), duration: number( record.duration ), name: String( record.passengerName ), email: String( record.passengerEmail ), phone: String( record.passengerPhone || "" ), notes: String( record.notes || "" ), status: String( record.status ), tripDetails: JSON.stringify( record.tripDetails || {} ), chauffeurId: chauffeurRecord ? String( chauffeurRecord.legacyId ) : null, smsConsentVersion: nullable( record.smsConsentVersion ), smsConsentedAt: nullable( record.smsConsentedAt ), pin: nullable( record.pin ), pinConfirmedAt: nullable( record.pinConfirmedAt ), createdAt: date( record.sourceCreatedAt || record.created ) }; }
function discount( record: Record<string, unknown> ): DiscountCodeRecord { return { id: number( record.legacyId ), code: String( record.code ), label: String( record.label ), kind: record.kind as "percent" | "fixed", value: number( record.value ), active: Number( Boolean( record.active ) ), maxRedemptions: record.maxRedemptions == null || record.maxRedemptions === "" ? null : number( record.maxRedemptions ), redemptions: number( record.redemptions ), expiresAt: nullable( record.expiresAt ), createdAt: date( record.sourceCreatedAt || record.created ), updatedAt: date( record.sourceUpdatedAt || record.updated ) }; }
function block( record: Record<string, unknown> ): BlockedSlotRecord { const chauffeurRecord = record.expand && typeof record.expand === "object" ? ( record.expand as Record<string, unknown> ).chauffeur as Record<string, unknown> | undefined : undefined; return { id: number( record.legacyId ), title: String( record.title ), date: String( record.startDate ), endDate: nullable( record.endDate ) || undefined, isFullDay: Number( Boolean( record.isFullDay ) ), time: String( record.startTime || "" ), duration: number( record.duration ), recurring: String( record.recurring ), chauffeurId: chauffeurRecord ? String( chauffeurRecord.legacyId ) : null, createdAt: date( record.sourceCreatedAt || record.created ) }; }
async function chauffeurRelation( id?: string | null ) { if ( !id ) return ""; return ( await first( pocketBaseCollections.chauffeurs, "legacyId = {:id}", { id } ) )?.id || ""; }
async function vehicleRelation( id?: number | null ) { if ( !id ) return ""; return ( await first( pocketBaseCollections.vehicles, "legacyId = {:id}", { id } ) )?.id || ""; }

export async function getAllChauffeurs() { return ( await pb().collection( pocketBaseCollections.chauffeurs ).getFullList( { filter: "status = 'active'", sort: "name", expand: "vehicle" } ) ).map( chauffeur ); }
export async function getChauffeurById( id: string ) { const row = await first( pocketBaseCollections.chauffeurs, "legacyId = {:id} && status = 'active'", { id } ); return row ? chauffeur( row ) : undefined; }
export async function getChauffeurByEmail( email: string ) { const row = await first( pocketBaseCollections.chauffeurs, "email = {:email} && status = 'active'", { email: email.trim().toLowerCase() } ); return row ? chauffeur( row ) : undefined; }
export async function getAllVehicles() { return ( await pb().collection( pocketBaseCollections.vehicles ).getFullList( { sort: "make,model" } ) ).map( vehicle ); }
export async function getVehicleById( id: number ) { const row = await first( pocketBaseCollections.vehicles, "legacyId = {:id}", { id } ); return row ? vehicle( row ) : undefined; }
export async function getAllBookings() { return ( await pb().collection( pocketBaseCollections.bookings ).getFullList( { sort: "-created", expand: "chauffeur" } ) ).map( booking ); }
export async function getBookingsForChauffeur( chauffeurId: string ) { const relation = await chauffeurRelation( chauffeurId ); if ( !relation ) return []; return ( await pb().collection( pocketBaseCollections.bookings ).getFullList( { filter: pb().filter( "chauffeur = {:chauffeur}", { chauffeur: relation } ), sort: "-created", expand: "chauffeur" } ) ).map( booking ); }
export async function getBookingByReference( reference: string ) { const row = await first( pocketBaseCollections.bookings, "reference = {:reference}", { reference } ); return row ? booking( row ) : undefined; }
export async function createVehicle( input: Pick<VehicleRecord, "make" | "model"> & Partial<Pick<VehicleRecord, "year" | "colour" | "plate">> ) { return vehicle( await createWithLegacyId( pocketBaseCollections.vehicles, { make: input.make.trim(), model: input.model.trim(), year: input.year ?? null, colour: input.colour?.trim() || "", plate: input.plate?.trim() || "", status: "active", sourceCreatedAt: new Date().toISOString() } ) ); }
export async function updateVehicle( id: number, updates: Partial<Pick<VehicleRecord, "make" | "model" | "year" | "colour" | "plate" | "status">> ) { const row = await first( pocketBaseCollections.vehicles, "legacyId = {:id}", { id } ); if ( !row ) return false; await pb().collection( pocketBaseCollections.vehicles ).update( row.id, { make: updates.make?.trim() ?? row.make, model: updates.model?.trim() ?? row.model, year: updates.year === undefined ? row.year : updates.year ?? null, colour: updates.colour === undefined ? row.colour : updates.colour?.trim() || "", plate: updates.plate === undefined ? row.plate : updates.plate?.trim() || "", status: updates.status ?? row.status } ); return true; }
export async function deleteVehicle( id: number ) { const row = await first( pocketBaseCollections.vehicles, "legacyId = {:id}", { id } ); if ( !row ) return false; const assigned = await pb().collection( pocketBaseCollections.chauffeurs ).getFullList( { filter: pb().filter( "vehicle = {:vehicle}", { vehicle: row.id } ), fields: "id" } ); await Promise.all( assigned.map( c => pb().collection( pocketBaseCollections.chauffeurs ).update( c.id, { vehicle: "" } ) ) ); await pb().collection( pocketBaseCollections.vehicles ).delete( row.id ); return true; }
export async function assignVehicleToChauffeur( chauffeurId: string | null, vehicleId: number ) { const v = await vehicleRelation( vehicleId ); if ( !v ) throw new Error( "Vehicle not found" ); const existing = await pb().collection( pocketBaseCollections.chauffeurs ).getFullList( { filter: pb().filter( "vehicle = {:vehicle}", { vehicle: v } ), fields: "id" } ); await Promise.all( existing.map( c => pb().collection( pocketBaseCollections.chauffeurs ).update( c.id, { vehicle: "" } ) ) ); if ( !chauffeurId ) return true; const c = await first( pocketBaseCollections.chauffeurs, "legacyId = {:id} && status = 'active'", { id: chauffeurId } ); if ( !c ) return false; await pb().collection( pocketBaseCollections.chauffeurs ).update( c.id, { vehicle: v } ); return true; }
export async function unassignVehicle( vehicleId: number ) { await assignVehicleToChauffeur( null, vehicleId ); }
export async function updateBookingStatus( reference: string, status: string ) { const row = await first( pocketBaseCollections.bookings, "reference = {:reference}", { reference } ); if ( !row || row.status === status ) return false; await pb().collection( pocketBaseCollections.bookings ).update( row.id, { status } ); return true; }
export async function updateBookingChauffeur( reference: string, chauffeurId: string | null ) { const row = await first( pocketBaseCollections.bookings, "reference = {:reference}", { reference } ); if ( !row ) return false; await pb().collection( pocketBaseCollections.bookings ).update( row.id, { chauffeur: await chauffeurRelation( chauffeurId ) } ); return true; }
export async function updateBookingSchedule( reference: string, schedule: { date: string; time: string; duration?: number } ) { assertFutureBookingTime( schedule.date, schedule.time, new Date(), await getNotificationTimeZone() ); const row = await first( pocketBaseCollections.bookings, "reference = {:reference}", { reference } ); if ( !row ) return false; await pb().collection( pocketBaseCollections.bookings ).update( row.id, { pickupDate: schedule.date, pickupTime: schedule.time, duration: schedule.duration ?? row.duration } ); return true; }
export async function deleteBooking( reference: string ) { const row = await first( pocketBaseCollections.bookings, "reference = {:reference}", { reference } ); if ( !row ) return false; await pb().collection( pocketBaseCollections.bookings ).delete( row.id ); return true; }
export async function confirmBookingPin( reference: string, pin: string ) { const row = await first( pocketBaseCollections.bookings, "reference = {:reference}", { reference } ); if ( !row ) return { success: false, error: "Booking not found" }; if ( !row.pin || row.pin !== pin ) return { success: false, error: "Invalid PIN. Please try again." }; await pb().collection( pocketBaseCollections.bookings ).update( row.id, { status: "confirmed", pinConfirmedAt: new Date().toISOString() } ); return { success: true }; }
export async function saveBooking( input: Omit<BookingRecord, "id" | "createdAt"> & { discountCode?: string | null } ) { assertFutureBookingTime( input.date, input.time, new Date(), await getNotificationTimeZone() ); const details = JSON.parse( input.tripDetails || "{}" ) as Record<string, unknown>; if ( input.discountCode?.trim() ) { const code = await getDiscountCodeByCode( input.discountCode ); const subtotal = Number( details.estimatedTotal ?? details.estimatedPrice ?? 0 ) * 100; if ( !code || !code.active ) throw new DiscountCodeError( "Invalid discount code" ); if ( code.expiresAt && new Date( code.expiresAt ).getTime() <= Date.now() ) throw new DiscountCodeError( "Discount code has expired" ); if ( code.maxRedemptions !== null && code.redemptions >= code.maxRedemptions ) throw new DiscountCodeError( "Discount code has reached its redemption limit" ); if ( !Number.isFinite( subtotal ) || subtotal <= 0 ) throw new DiscountCodeError( "Discount codes require a quoted booking total" ); const amount = code.kind === "percent" ? Math.min( subtotal, Math.round( subtotal * code.value / 100 ) ) : Math.min( subtotal, code.value ); details.discountCode = code.code; details.discountAmountCents = amount; details.originalEstimatedTotal = subtotal / 100; details.estimatedTotal = ( subtotal - amount ) / 100; const source = await first( pocketBaseCollections.discounts, "legacyId = {:id}", { id: code.id } ); if ( source ) await pb().collection( pocketBaseCollections.discounts ).update( source.id, { redemptions: code.redemptions + 1 } ); }
  const created = await createWithLegacyId( pocketBaseCollections.bookings, { reference: input.reference, tripType: input.tripType, pickupDate: input.date, pickupTime: input.time, duration: input.duration, passengerName: input.name, passengerEmail: input.email, passengerPhone: input.phone || "", notes: input.notes || "", status: input.status, tripDetails: details, chauffeur: await chauffeurRelation( input.chauffeurId ), smsConsentVersion: input.smsConsentVersion || "", smsConsentedAt: input.smsConsentedAt || "", pin: input.pin || String( Math.floor( Math.random() * 10000 ) ).padStart( 4, "0" ), sourceCreatedAt: new Date().toISOString() } ); return booking( created ); }
export async function getAppSetting( key: string ) { const row = await first( pocketBaseCollections.settings, "key = {:key}", { key } ); return row ? String( row.value ) : null; }
export async function setAppSetting( key: string, value: string ) { const row = await first( pocketBaseCollections.settings, "key = {:key}", { key } ); if ( row ) await pb().collection( pocketBaseCollections.settings ).update( row.id, { value, sourceUpdatedAt: new Date().toISOString() } ); else await pb().collection( pocketBaseCollections.settings ).create( { key, value, sourceUpdatedAt: new Date().toISOString() } ); }
export async function getAllDiscountCodes() { return ( await pb().collection( pocketBaseCollections.discounts ).getFullList( { sort: "-created" } ) ).map( discount ); }
export async function getDiscountCodeByCode( code: string ) { const row = await first( pocketBaseCollections.discounts, "code = {:code}", { code: normalizeDiscountCode( code ) } ); return row ? discount( row ) : undefined; }
export async function getAllBlockedSlots() { return ( await pb().collection( pocketBaseCollections.blockedSlots ).getFullList( { sort: "-created", expand: "chauffeur" } ) ).map( block ); }
export async function getBlockedSlotsForChauffeur( chauffeurId: string ) { const relation = await chauffeurRelation( chauffeurId ); return ( await pb().collection( pocketBaseCollections.blockedSlots ).getFullList( { filter: relation ? pb().filter( "chauffeur = '' || chauffeur = {:chauffeur}", { chauffeur: relation } ) : "chauffeur = ''", sort: "-created", expand: "chauffeur" } ) ).map( block ); }
export async function saveBlockedSlot( input: Omit<BlockedSlotRecord, "id" | "createdAt"> ) { return block( await createWithLegacyId( pocketBaseCollections.blockedSlots, { title: input.title, startDate: input.date, endDate: input.endDate || "", isFullDay: Boolean( input.isFullDay ), startTime: input.time, duration: input.duration, recurring: input.recurring, chauffeur: await chauffeurRelation( input.chauffeurId ), sourceCreatedAt: new Date().toISOString() } ) ); }
export async function deleteBlockedSlot( id: number ) { const row = await first( pocketBaseCollections.blockedSlots, "legacyId = {:id}", { id } ); if ( !row ) return false; await pb().collection( pocketBaseCollections.blockedSlots ).delete( row.id ); return true; }
export async function deleteChauffeurBlockedSlot( id: number, chauffeurId: string ) { const row = await first( pocketBaseCollections.blockedSlots, "legacyId = {:id}", { id } ); if ( !row || String( row.chauffeur ) !== await chauffeurRelation( chauffeurId ) ) return false; await pb().collection( pocketBaseCollections.blockedSlots ).delete( row.id ); return true; }
export async function getBookingBufferMinutes() { const raw = await getAppSetting( "bookingBufferMinutes" ); const parsed = Number( raw ); return Number.isFinite( parsed ) && parsed >= 0 ? parsed : DEFAULT_BOOKING_BUFFER_MINUTES; }
export async function checkBookingClash( dateValue: string, time: string, duration: number, chauffeurId?: string | null ) { const bookings = chauffeurId ? await getBookingsForChauffeur( chauffeurId ) : await getAllBookings(); const zone = await getNotificationTimeZone(); const start = zonedDateTimeToDate( dateValue, time, zone ).getTime(), end = start + duration * 60_000, buffer = await getBookingBufferMinutes() * 60_000; const conflictingBooking = bookings.find( item => item.date === dateValue && ![ "cancelled", "rejected" ].includes( item.status ) && start < zonedDateTimeToDate( item.date, item.time, zone ).getTime() + item.duration * 60_000 + buffer && end + buffer > zonedDateTimeToDate( item.date, item.time, zone ).getTime() ); return conflictingBooking ? { clash: true, conflictingBooking } : { clash: false }; }
export async function checkBlockedClash( dateValue: string, time: string, duration: number, chauffeurId?: string | null ) { const blocks = chauffeurId ? await getBlockedSlotsForChauffeur( chauffeurId ) : await getAllBlockedSlots(); const zone = await getNotificationTimeZone(); const start = zonedDateTimeToDate( dateValue, time, zone ).getTime(), end = start + duration * 60_000; const conflictingBlock = blocks.find( item => { const applies = item.recurring === "daily" || ( item.recurring === "none" && dateValue >= item.date && ( !item.endDate || dateValue <= item.endDate ) ) || ( item.recurring === "weekends" && [ 0, 6 ].includes( zonedDateTimeToDate( dateValue, "00:00", zone ).getDay() ) ) || ( item.recurring === "weekly" && zonedDateTimeToDate( item.date, "00:00", zone ).getDay() === zonedDateTimeToDate( dateValue, "00:00", zone ).getDay() ); if ( !applies ) return false; if ( item.isFullDay ) return true; const blockStart = zonedDateTimeToDate( dateValue, item.time, zone ).getTime(); return start < blockStart + item.duration * 60_000 && end > blockStart; } ); return conflictingBlock ? { clash: true, conflictingBlock } : { clash: false }; }
export async function findAvailableChauffeur( dateValue: string, time: string, duration: number ) { for ( const item of await getAllChauffeurs() ) { if ( !( await checkBookingClash( dateValue, time, duration, item.id ) ).clash && !( await checkBlockedClash( dateValue, time, duration, item.id ) ).clash ) return item; } return null; }
export async function createChauffeur( input: Pick<ChauffeurRecord, "name" | "email" | "phone"> & { password: string; avatarUrl?: string | null } ) { if ( await getChauffeurByEmail( input.email ) ) throw new Error( "A chauffeur with this email already exists" ); const id = randomUUID(); const user = await pb().collection( pocketBaseCollections.users ).create( { email: input.email.trim().toLowerCase(), password: input.password, passwordConfirm: input.password, name: input.name.trim(), legacyUserId: `chauffeur:${ id }`, role: "chauffeur", status: "active", chauffeurId: id } ); const record = await pb().collection( pocketBaseCollections.chauffeurs ).create( { legacyId: id, user: user.id, name: input.name.trim(), email: input.email.trim().toLowerCase(), phone: input.phone || "", status: "active", avatarUrl: input.avatarUrl || "" } ); return chauffeur( record ); }
export async function updateChauffeur( id: string, updates: { name?: string; email?: string; phone?: string | null; password?: string | null } ) { const record = await first( pocketBaseCollections.chauffeurs, "legacyId = {:id} && status = 'active'", { id } ); if ( !record ) return undefined; const data = { name: updates.name?.trim() ?? record.name, email: updates.email?.trim().toLowerCase() ?? record.email, phone: updates.phone === undefined ? record.phone : updates.phone || "" }; const updated = await pb().collection( pocketBaseCollections.chauffeurs ).update( record.id, data ); if ( record.user ) await pb().collection( pocketBaseCollections.users ).update( String( record.user ), { ...data, ...( updates.password?.trim() ? { password: updates.password.trim(), passwordConfirm: updates.password.trim() } : {} ) } ); return chauffeur( updated ); }
export async function updateChauffeurAvatar( id: string, avatarUrl: string | null ) { const record = await first( pocketBaseCollections.chauffeurs, "legacyId = {:id} && status = 'active'", { id } ); if ( !record ) return undefined; return chauffeur( await pb().collection( pocketBaseCollections.chauffeurs ).update( record.id, { avatarUrl: avatarUrl || "" } ) ); }
export async function deleteChauffeur( id: string ) { const record = await first( pocketBaseCollections.chauffeurs, "legacyId = {:id} && status = 'active'", { id } ); if ( !record ) return false; const bookings = await pb().collection( pocketBaseCollections.bookings ).getFullList( { filter: pb().filter( "chauffeur = {:chauffeur}", { chauffeur: record.id } ), fields: "id" } ); await Promise.all( bookings.map( item => pb().collection( pocketBaseCollections.bookings ).update( item.id, { chauffeur: "" } ) ) ); await pb().collection( pocketBaseCollections.blockedSlots ).getFullList( { filter: pb().filter( "chauffeur = {:chauffeur}", { chauffeur: record.id } ), fields: "id" } ).then( rows => Promise.all( rows.map( item => pb().collection( pocketBaseCollections.blockedSlots ).delete( item.id ) ) ) ); await pb().collection( pocketBaseCollections.chauffeurs ).update( record.id, { status: "inactive", vehicle: "" } ); if ( record.user ) await pb().collection( pocketBaseCollections.users ).update( String( record.user ), { status: "inactive" } ); return true; }
function payment( record: Record<string, unknown>, bookingRecord?: BookingRecord ): PaymentRecord { return { id: number( record.legacyId ), bookingReference: String( record.bookingReference ), amountCents: number( record.amountCents ), currency: String( record.currency ), method: String( record.method ), status: String( record.status ), transactionReference: nullable( record.transactionReference ), notes: nullable( record.notes ), paidAt: nullable( record.paidAt ), createdAt: date( record.sourceCreatedAt || record.created ), updatedAt: date( record.sourceUpdatedAt || record.updated ), ...( bookingRecord ? { customerName: bookingRecord.name, customerEmail: bookingRecord.email, tripType: bookingRecord.tripType, tripDate: bookingRecord.date, tripTime: bookingRecord.time, bookingStatus: bookingRecord.status, tripDetails: bookingRecord.tripDetails } : {} ) }; }
export async function getAllPayments() { const rows = await pb().collection( pocketBaseCollections.payments ).getFullList( { sort: "-created", expand: "booking" } ); return rows.map( row => payment( row, row.expand?.booking ? booking( row.expand.booking as Record<string, unknown> ) : undefined ) ); }
export async function createPayment( input: { bookingReference: string; amountCents: number; currency?: string; method: string; status: string; transactionReference?: string | null; notes?: string | null } ) { const bookingRow = await first( pocketBaseCollections.bookings, "reference = {:reference}", { reference: input.bookingReference } ); if ( !bookingRow ) throw new Error( "Booking not found" ); if ( bookingRow.status === "cancelled" ) throw new Error( "Cannot record a payment for a cancelled booking" ); const row = await createWithLegacyId( pocketBaseCollections.payments, { booking: bookingRow.id, bookingReference: input.bookingReference, amountCents: input.amountCents, currency: input.currency || "USD", method: input.method, status: input.status, transactionReference: input.transactionReference || "", notes: input.notes || "", paidAt: input.status === "paid" ? new Date().toISOString() : "", sourceCreatedAt: new Date().toISOString(), sourceUpdatedAt: new Date().toISOString() } ); if ( input.status === "paid" && ![ "confirmed", "accepted" ].includes( String( bookingRow.status ) ) ) await pb().collection( pocketBaseCollections.bookings ).update( bookingRow.id, { status: "confirmed" } ); return payment( row, booking( bookingRow ) ); }
export async function updatePayment( id: number, updates: Partial<{ amountCents: number; method: string; status: string; transactionReference: string | null; notes: string | null }> ) { const row = await first( pocketBaseCollections.payments, "legacyId = {:id}", { id } ); if ( !row ) return false; const next = updates.status ?? String( row.status ); await pb().collection( pocketBaseCollections.payments ).update( row.id, { amountCents: updates.amountCents ?? row.amountCents, method: updates.method ?? row.method, status: next, transactionReference: updates.transactionReference === undefined ? row.transactionReference : updates.transactionReference || "", notes: updates.notes === undefined ? row.notes : updates.notes || "", paidAt: next === "paid" ? row.paidAt || new Date().toISOString() : "", sourceUpdatedAt: new Date().toISOString() } ); if ( next === "paid" ) { const bookingRow = await first( pocketBaseCollections.bookings, "reference = {:reference}", { reference: String( row.bookingReference ) } ); if ( bookingRow && bookingRow.status !== "cancelled" ) await pb().collection( pocketBaseCollections.bookings ).update( bookingRow.id, { status: "confirmed" } ); } return true; }
export async function deletePayment( id: number ) { const row = await first( pocketBaseCollections.payments, "legacyId = {:id}", { id } ); if ( !row ) return false; await pb().collection( pocketBaseCollections.payments ).delete( row.id ); return true; }
export async function createDiscountCode( input: { code: string; label: string; kind: "percent" | "fixed"; value: number; active?: boolean; maxRedemptions?: number | null; expiresAt?: string | null } ) { return discount( await createWithLegacyId( pocketBaseCollections.discounts, { code: normalizeDiscountCode( input.code ), label: input.label.trim(), kind: input.kind, value: input.value, active: input.active !== false, maxRedemptions: input.maxRedemptions ?? null, redemptions: 0, expiresAt: input.expiresAt || "", sourceCreatedAt: new Date().toISOString(), sourceUpdatedAt: new Date().toISOString() } ) ); }
export async function updateDiscountCode( id: number, updates: Partial<{ code: string; label: string; kind: "percent" | "fixed"; value: number; active: boolean; maxRedemptions: number | null; expiresAt: string | null }> ) { const row = await first( pocketBaseCollections.discounts, "legacyId = {:id}", { id } ); if ( !row ) return false; await pb().collection( pocketBaseCollections.discounts ).update( row.id, { code: updates.code === undefined ? row.code : normalizeDiscountCode( updates.code ), label: updates.label?.trim() ?? row.label, kind: updates.kind ?? row.kind, value: updates.value ?? row.value, active: updates.active ?? row.active, maxRedemptions: updates.maxRedemptions === undefined ? row.maxRedemptions : updates.maxRedemptions, expiresAt: updates.expiresAt === undefined ? row.expiresAt : updates.expiresAt || "", sourceUpdatedAt: new Date().toISOString() } ); return true; }
export async function deleteDiscountCode( id: number ) { const row = await first( pocketBaseCollections.discounts, "legacyId = {:id}", { id } ); if ( !row ) return false; await pb().collection( pocketBaseCollections.discounts ).delete( row.id ); return true; }
export async function getDiscountCodesWithUsage() { return ( await getAllDiscountCodes() ).map( item => ( { ...item, usages: [], trackedRedemptions: item.redemptions, totalDiscountCents: 0, totalRevenueCents: 0 } ) ); }
